# -*- coding: utf-8 -*-
"""site爬蟲

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YydRzMyjaQT8Od3rno-HZui0OiVhP6zt
"""

pip install requests beautifulsoup4

import requests
from bs4 import BeautifulSoup
import json
import datetime

def fetch_financial_news():
    # 我們先以 Yahoo 財經新聞為目標網站
    url = "https://tw.stock.yahoo.com/news/"

    # 設定 User-Agent 偽裝成一般瀏覽器，避免被網站阻擋
    headers = {
        "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36"
    }

    try:
        print("開始抓取新聞...")
        response = requests.get(url, headers=headers)
        response.raise_for_status() # 檢查是否有連線錯誤

        soup = BeautifulSoup(response.text, 'html.parser')
        news_list = []

        # 尋找所有包含新聞連結的 <a> 標籤
        # 注意：實際的 class 名稱會隨網站改版而變動，這裡使用 href 包含 /news/ 來過濾
        articles = soup.select('a[href*="/news/"]')

        for article in articles:
            title = article.text.strip()
            link = article.get('href')

            # 過濾掉太短的無效標題，並確保不抓到重複的新聞
            if title and len(title) > 8 and not any(n['link'] == link for n in news_list):
                # 確保連結是完整的 URL
                if not link.startswith('http'):
                    link = "https://tw.stock.yahoo.com" + link

                news_list.append({
                    "title": title,
                    "link": link,
                    "date": datetime.datetime.now().strftime("%Y-%m-%d %H:%M") # 暫時標記爬取當下的時間
                })

            # 我們先抓最新的 5 則就好
            if len(news_list) >= 5:
                break

        # 將抓到的資料存成 news.json 檔案
        with open('news.json', 'w', encoding='utf-8') as f:
            json.dump(news_list, f, ensure_ascii=False, indent=4)

        print(f"✅ 成功抓取 {len(news_list)} 則新聞，已儲存至 news.json！")

    except Exception as e:
        print(f"❌ 抓取過程中發生錯誤: {e}")

if __name__ == "__main__":
    fetch_financial_news()